post:
  tags:
    - Services registration API
  summary: Register user settings service
  operationId: registerService
  requestBody:
    content:
      application/json:
        schema:
          type: object
          required:
            - data
          properties:
            data:
              type: object
              $ref: '#/components/schemas/UserSettingsService'
    responses:
      '200':
        description: Success
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  $ref: '#/components/schemas/UserSettingsService'